### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError

### ISSUE THREAD

**Issue by tobiascz** [hangzhaomit/HACS-dataset#5]
For some of the videos I get the error:
```
Downloading video: https://www.youtube.com/watch?v=T11Rmq-r3h0
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/tobiascz/miniconda3/envs/kinetics/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/home/tobiascz/miniconda3/envs/kinetics/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/tobiascz/miniconda3/envs/kinetics/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/tobiascz/miniconda3/envs/kinetics/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error processing [Slacklining/T11Rmq-r3h0]: 'streams'
```
Iam using youtuble-dl 2019.05.20.
So far I am not sure where this is coming from.

**Comment by hangzhaomit** [comment]
Please use ```pip install -U youtube-dl``` to update your software version. The newest version 2019.07.02 works.
